version: '3.5'
services:
  app:
    container_name: chat_front
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/code
      - chat_yarn_cache:/code/node_modules
    entrypoint: ["sh", "./start.sh"]

volumes:
  chat_yarn_cache:
